HGU-ZERO/Glang

lib/api/chatgpt_service.dart
lib/view/chat/chat_screen.dart
lib/view/components/custom_button.dart
lib/view/components/message_bubble.dart

- chat_screen.dart의 말풍선, components/message_bubble.dart 로 컴포넌트화
- 파일 상단 설명 추가
- my_button.dart => custom_button.dart 파일명 변경
- custom_button: borderRadius = 10 변경.

[Refactor] chat 말풍선 컴포넌트화 (24.12.31)

---

android/app/src/main/AndroidManifest.xml
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
ios/Runner.xcworkspace/contents.xcworkspacedata
ios/Runner/AppDelegate.swift
ios/Runner/Base.lproj/Main.storyboard
lib/main.dart
lib/view/home/home.dart
lib/viewmodel/notification_controller.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

- main.dart 수정
- viewmodel/notification_controller.dart 추가
- view/home/home.dart 예시코드 추가
- pubspec.yaml 패키지 추가
-   permission_handler: ^11.1.0 # 권한 처리, flutter_local_notifications: ^16.3.0 # local 알림 설정

[Feat] Local Notification 설정 (24.12.31)

---

lib/app.dart
lib/localization/l10n/en.json
lib/localization/l10n/ko.json
lib/theme/theme.dart
lib/view/chat/chat_screen.dart
lib/view/community/community_main.dart
lib/view/components/custom_app_bar.dart
lib/view/components/custom_navigation_bar.dart
lib/view/components/custom_tap_bar.dart
lib/view/course/course_main.dart
lib/view/home/home.dart
lib/view/mypage/mypage_main.dart
lib/view/mypage/settings_page.dart
lib/viewmodel/custom_colors_provider.dart
pubspec.yaml

- /mypage/settings_page.dart 에 추가.
- Design System에 맞게 AppBar 컴포넌트 수정

[Feat] AppBar 업데이트. Setting 페이지 추가.

---

lib/theme/theme.dart

Color Pallette 반영
- primary60
- primary40
- primary20
- primary10
- neutral80

[Feat] theme.dart 컬러 팔레트 추가 (2025.01.03)

---

lib/util/box_shadow_styles.dart
lib/view/course/course_main.dart
lib/view/course/course_subdetail.dart
lib/view/course/section.dart
lib/view/util/box_shadow_styles.dart
pubspec.lock

course modified

---

lib/view/course/course_main.dart
lib/view/course/course_subdetail.dart
lib/view/course/section.dart

[Feat] course_main.dart, section.dart, course_subdetail.dart 수정 (1/6)

---

lib/view/course/course_subdetail.dart

[Feat] course_subdetail.dart UI 디테일 수정 (1/6)

---

lib/theme/theme.dart
lib/util/box_shadow_styles.dart
lib/view/components/custom_app_bar.dart
lib/view/components/custom_button.dart
lib/view/components/custom_learning_card.dart
lib/view/course/section.dart
lib/view/home/home.dart
lib/view/util/box_shadow_styles.dart

- theme.dart accent 수정
- home.dart UI 제작 시작
- custom app bar, custom button 수정, custom learning card 추가
- course/section.dart 클릭 / hover 시 색상 변경

[Feat] theme수정, home UI시작, component수정, course/section수정 (2025.01.06)

---

lib/app.dart
lib/model/section_data.dart
lib/theme/theme.dart
lib/view/components/custom_learning_card.dart
lib/view/course/course_main.dart
lib/view/course/popup_component.dart
lib/view/course/section.dart
lib/view/home/example.dart
lib/view/home/home.dart

- course 컴포넌트화
- theme error 추가

[Feat] course 변경 (2025.01.07)

---

lib/view/feature/after_read/AR_main.dart
lib/view/feature/after_read/GA_03_02_content_summary/CS_learning.dart
lib/view/feature/after_read/GA_03_02_content_summary/CS_main.dart
lib/view/feature/after_read/GA_03_06_writing_essay/WE_learning.dart
lib/view/feature/after_read/GA_03_06_writing_essay/WE_main.dart
lib/view/feature/after_read/GA_03_07_format_conversion/FC_learning.dart
lib/view/feature/after_read/GA_03_07_format_conversion/FC_main.dart

[Feat] GA_03_02, 06, 07 기본 코드 추가 (25.01.15)

[Feat] GA_03_02, 06, 07 기본 코드 추가 (25.01.15)

---

lib/theme/theme.dart
lib/view/feature/after_read/GA_03_06_writing_essay/WE_learning.dart

[Feat] theme.dart: success40, error40 추가 (25.01.16)

[Feat] theme.dart: success40, error40 추가 (25.01.16)

---

lib/view/components/custom_app_bar.dart

[Feat] 아이콘 추가, 로그인 화면 변경, 각 화면 SafeArea 설정 (25.01.16)

[Feat] custom_app_bar 로고 수정 (25.01.16)

---

lib/view/feature/after_read/widget/answer_section.dart

[Feat] Answer_Section 수정 (25.01.16)

[Feat] Answer_Section 수정 (25.01.16)

---

lib/theme/theme.dart
lib/util/gradients.dart
lib/view/components/custom_button.dart
lib/view/feature/after_read/GA_03_02_content_summary/CS_learning.dart
lib/view/mypage/info/info_badge.dart

[Feat] CS-learning완료, secondary60 색상 추가(25.01.17)

[Feat] CS-learning완료, secondary60 색상 추가(25.01.17)

---

lib/view/feature/after_read/GA_03_03_debate_activity/DA_main.dart
lib/view/feature/after_read/GA_03_04_diagram/diagram_learning.dart
lib/view/feature/after_read/GA_03_05_writing_form/writing_form_learning.dart
lib/view/feature/after_read/GA_03_08_paragraph_analysis/paragraph_analysis_result.dart
lib/view/feature/after_read/GA_03_09_review_writing/review_writing.dart
lib/view/feature/after_read/widget/start_page/icon_section_main.dart
lib/view/home/home.dart

[Feat] 토론 시작 페이지, GA_03 pop 루트 변경 (25.01.21)

[Feat] 토론 시작 페이지, GA_03 pop 루트 변경 (25.01.21)

---

lib/api/debate_chatgpt_service.dart
lib/view/course/course_main.dart
lib/view/feature/after_read/GA_03_03_debate_activity/DA_learning.dart
lib/view/feature/after_read/GA_03_03_debate_activity/widgets/alert_dialog.dart
lib/view/feature/after_read/GA_03_03_debate_activity/widgets/debate_notifier.dart
lib/view/feature/after_read/choose_activities.dart
pubspec.lock
pubspec.yaml

[[Feat] 토론 파트 라운드제 추가 (25.01.23)]

[Feat] 토론 파트 라운드제 추가 (25.01.23)

---

lib/theme/font.dart
lib/view/components/message_bubble.dart
lib/view/feature/after_read/GA_03_03_debate_activity/DA_learning.dart
lib/view/feature/after_read/GA_03_03_debate_activity/widgets/alert_dialog.dart
lib/view/feature/after_read/GA_03_03_debate_activity/widgets/debate_notifier.dart
pubspec.yaml

[[Feat] NotoSerif 폰트 추가 (25.01.23)]

[Feat] NotoSerif 폰트 추가 (25.01.23)

---

lib/view/home/attendance_model.dart
lib/view/home/attendance_provider.dart
lib/view/home/attendance_repository.dart
lib/view/home/attendance_service.dart
lib/view/home/home.dart
lib/view/login/auth_controller.dart
lib/view/login/login_main.dart

[Feat] 출석체크 기능 구현 (25.02.03)

---

lib/model/section_data.dart
lib/model/stage_data.dart
lib/view/course/course_main.dart
lib/view/course/popup_component.dart
lib/view/course/section.dart
lib/view/home/home.dart
lib/viewmodel/section_provider.dart

[[Feat] 진행상황 저장하기를 위한 데이터 모델 수정 (25.02.04)](https://github.com/HGU-ZERO/Glang/commit/aee5380d7d04148a2cc93fe3871c34e3ad08dd30)

[Feat] 진행상황 저장하기를 위한 데이터 모델 수정 (25.02.04)

---

lib/app.dart
lib/model/reading_data.dart
lib/model/stage_data.dart
lib/view/components/custom_button.dart
lib/view/course/course_subdetail.dart
lib/view/feature/reading/GA_02/RD_main.dart
lib/view/feature/reading/quiz_data.dart
lib/view/feature/reading/stage_data.dart

[Feat] 읽기 중 활동 DB연결 완료 (25.02.06)

[Feat] 읽기 중 활동 DB연결 완료 (25.02.06)

---

lib/model/stage_data.dart
lib/view/feature/after_read/choose_activities.dart
lib/view/feature/after_read/choose_activities_backup.dart

[Feat] 읽기 후 choose activities, DB와 연결 완료 (25.02.07)

[Feat] 읽기 후 choose activities, DB와 연결 완료 (25.02.07)

---

lib/model/stage_data.dart
lib/view/feature/after_read/GA_03_04_diagram/diagram_backup.dart
lib/view/feature/after_read/GA_03_04_diagram/diagram_learning.dart
lib/view/feature/after_read/GA_03_04_diagram/submission_notifier.dart
lib/view/home/stage_provider.dart

[Feat] diagram 오류 해결 (25.02.12)

[Feat] diagram 오류 해결 (25.02.12)

---

lib/model/section_data.dart
lib/model/stage_data.dart
lib/view/feature/after_read/GA_03_03_debate_activity/DA_learning.dart

[[Feat] 실제 데이터 값 삽입 (25.02.12)](https://github.com/HGU-ZERO/Glang/commit/61b7e609854b03d634d976ed1c65156acff21514)

[Feat] 실제 데이터 값 삽입 (25.02.12)

---

lib/view/login/auth_controller.dart
lib/view/mypage/settings/settings_secession.dart
lib/viewmodel/user_service.dart

[Feat] 회원 탈퇴 기능 오류 해결 (25.02.13)

[Feat] 회원 탈퇴 기능 오류 해결 (25.02.13)

---

android/app/google-services.json
android/app/src/main/res/mipmap-anydpi-v26/launcher_icon.xml
pubspec.yaml

[Feat] 아이콘 오류 해결 (25.02.14)

---

lib/view/feature/after_read/choose_activities.dart
lib/view/login/auth_controller.dart
lib/view/mypage/mypage_main.dart
lib/view/viewmodel/user_service.dart
lib/viewmodel/user_service.dart
pubspec.lock

[[Feat] 현재 코스 저장 (25.02.18)](https://github.com/HGU-ZERO/Glang/commit/0adcd0448a3ce90ddb95e8e89f0c4b84f9748f1f)

[Feat] 현재 코스 저장 (25.02.18)

---

lib/view/community/Board/CM_1depth_firebase.dart
lib/view/course/course_main.dart
lib/view/home/home.dart
lib/view/login/auth_controller.dart
lib/view/login/login_main.dart
lib/view/login/nickname_input.dart
lib/view/login/tutorial.dart
lib/view/mypage/mypage_main.dart
lib/view/widgets/DoubleBackToExitWrapper.dart

[Feat] 뒤로가기 두번 눌러서 앱 종료 (25.02.18)

[Feat] 뒤로가기 두번 눌러서 앱 종료 (25.02.18)

---

android/app/build.gradle
lib/app.dart
pubspec.yaml

[Feat] 자동로그인 시 출석체크 (25.02.19)

[Feat] 자동로그인 시 출석체크 (25.02.19)

---

lib/api/debate_chatgpt_service.dart
lib/view/feature/after_read/GA_03_03_debate_activity/DA_learning.dart
lib/view/home/home.dart
lib/view/widgets/auto_login_toggle.dart
lib/viewmodel/user_service.dart
pubspec.lock

[[Feat] 토론 프롬프트, 홈 개선 (25.02.19)]

[Feat] 토론 프롬프트, 홈 개선 (25.02.19)

---

lib/main.dart
lib/restart_widget.dart
lib/view/mypage/settings/settings_page.dart
lib/viewmodel/user_service.dart

[Feat] 로그아웃, 탈퇴 시 provider 초기화 되지않던 문제 해결 (25.02.19)

[Feat] 로그아웃, 탈퇴 시 provider 초기화 되지않던 문제 해결 (25.02.19)

---

lib/view/mypage/settings/settings_secession.dart

[Feat] Setting Secession 업데이트 (25.02.20)

[Feat] Setting Secession 업데이트 (25.02.20)

---

lib/api/chatgpt_service.dart
lib/api/debate_chatgpt_service.dart
lib/api/reading_chatbot_service.dart
lib/localization/app_localizations.dart
lib/model/ar_data.dart
lib/model/br_data.dart
lib/model/reading_data.dart

[Docs] 주석 추가 (25.02.21)
